sonar.organization=brahim-belghiti
sonar.projectKey=brahim-belghiti_banking_app
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=src/mocks/**,src/components/ui/**
sonar.javascript.lcov.reportPath=coverage/lcov.info